wanaku toolset add toolsets/currency.json -n "free-currency-conversion-tool" --description "Currency conversion tool" --uri "https://economia.awesomeapi.com.br/last/{parameter.value('fromCurrency')}-{parameter.value('toCurrency')}" --type http --property "fromCurrency:string,The currency to convert from using the 3 letter currency code" --property "toCurrency:string,The currency to convert to using the 3 letter currency code" --required fromCurrency --required toCurrency
wanaku toolset add toolsets/util.json -n "predict-age-tool" --description "Predict a person age by his or her name" --uri "https://api.agify.io?name={parameter.value('name')}" --type http --property "name:string,The name of the person to predict the name" --required name
wanaku toolset add toolsets/util.json -n "predict-gender-tool" --description "Predict a person gender by his or her name" --uri " https://api.genderize.io?name\={parameter.value('name')}" --type http --property "name:string,The name of the person to predict the gender" --required name
wanaku toolset add toolsets/util.json -n "predict-nationality-tool" --description "Predict a person nationality by his or her name" --uri " https://api.nationalize.io?name\={parameter.value('name')}" --type http --property "name:string,The name of the person to predict the nationality" --required name
wanaku toolset add toolsets/util.json -n "random-excuse-generator" --description "Generate random excuses" --uri "https://corporatebs-generator.sameerkumar.website/" --type http
wanaku toolset add toolsets/util.json -n "get-information-about-all-kinds-of-fruits" --description "Get information about all kinds of fruits" --uri "https://www.fruityvice.com/api/fruit/all" --type http
wanaku toolset add toolsets/util.json -n "get-information-about-specific-fruit" --description "Get information about a specific fruit" --uri "https://www.fruityvice.com/api/fruit/{parameter.value('fruit')}" --type http --property "fruit:string,The fruit to get the information from" --required fruit
wanaku toolset add toolsets/util.json -n "breweries-in-city" --description "Get a list of breweries from a given city" --uri "https://api.openbrewerydb.org/v1/breweries?by_city={parameter.value('city')}" --type http --property "city:string,The city to get the breweries" --required city
wanaku toolset add toolsets/util.json -n "product-information-by-barcode" --description "Get product information by barcode" --uri "https://world.openfoodfacts.org/api/v3/product/{parameter.value('barcode')}.json" --type http --property "barcode:string,The barcode of the product to search for information" --required barcode
wanaku toolset add toolsets/util.json -n "get-administrative-divisions-of-a-country" --description "Get the administrative divisions of a country" --uri "https://rawcdn.githack.com/kamikazechaser/administrative-divisions-db/master/api/{parameter.value('countryCode')}.json" --type http --property "countryCode:string,The 2 letter country code (i.e, BR for Brazil, US for United States, CZ for Czech Republic, etc)" --required countryCode
wanaku toolset add toolsets/development.json -n "list-public-api-providers" --description "Get a list of services providing free public APIs" --uri "https://api.apis.guru/v2/providers.json" --type http
wanaku toolset add toolsets/development.json -n "list-provider-apis" --description "Get a list of APIs from an specific provider" --uri "https://api.apis.guru/v2/{parameter.value('serviceProvider')}.json" --type http --property "serviceProvider:string,The name of the service provider serving the API" --required serviceProvider
wanaku toolset add toolsets/development.json -n "list-public-apis" --description "Get a list of free public APIs" --uri "https://api.apis.guru/v2/list.json" --type http
wanaku toolset add toolsets/development.json -n "dns-lookup-tool" --description "Look up DNS records for a hostname, domain name, or IP address on the public Internet" --uri "https://networkcalc.com/api/dns/lookup/{parameter.value('hostname')}" --type http --property "hostname:string,The hostname, IP address or domain to perform the lookup" --required hostname
wanaku toolset add toolsets/development.json -n "whois-lookup-tool" --description "Get the WHOIS registration information for a website's hostname, domain, or IP address" --uri "https://networkcalc.com/api/dns/whois/{parameter.value('hostname')}" --type http --property "hostname:string,The hostname, IP address or domain to get the WHOIS registration" --required hostname
wanaku toolset add toolsets/development.json -n "qr-code-generator" --description "Generate a QR code for URL of a website or address" --uri "https://www.qrtag.net/api/qr_64.png?url={parameter.value('url')}" --type http --property "url:string,The URL to generate the QR code" --required url
wanaku toolset add toolsets/development.json -n "email-verification" --description "Verify if an email address is legit" --uri "https://api.eva.pingutil.com/email?email={parameter.value('email')}" --type http --property "email:string,The email to verify" --required email
wanaku toolset add toolsets/development.json -n "estimate-site-carbon-footprint" --description "Estimate the carbon footprint for a website" --uri " https://api.websitecarbon.com/site?url={parameter.value('website')}" --type http --property "website:string,The website to estimate the carbon footprint" --required website
wanaku toolset add toolsets/web.json -n "digital-ocean-status" --description "Digital Ocean Status" --uri "https://status.digitalocean.com/api/v2/status.json" --type http
wanaku toolset add toolsets/web.json -n "digital-ocean-scheduled-maintenance" --description "Digital Ocean Scheduled Maintenances" --uri "https://status.digitalocean.com/api/v2/scheduled-maintenances.json" --type http
wanaku toolset add toolsets/web.json -n "digital-ocean-incidents" --description "Digital Ocean Incidents" --uri "https://status.digitalocean.com/api/v2/incidents/unresolved.json" --type http
wanaku toolset add toolsets/fun.json -n "popular-memes" --description "Get information about popular memes" --uri "https://api.imgflip.com/get_memes" --type http
wanaku toolset add toolsets/fun.json -n "random-useless-facts" --description "Get random useless facts" --uri "https://uselessfacts.jsph.pl/api/v2/facts/random?language=en" --type http
wanaku toolset add toolsets/fun.json -n "tech-sounding-phrases" --description "Get tech-savvy sounding phrases" --uri "https://techy-api.vercel.app/api/text" --type http
wanaku toolset add toolsets/mexico.json -n "mexico-zip-codes" --description "Get the zip code for a city from Mexico" --uri "https://sepomex.icalialabs.com/api/v1/zip_codes?city={parameter.value('city')}" --type http --property "city:string,The name of the mexican city to get the zip code" --required city
wanaku toolset add toolsets/brazil.json -n "geodetic-station" --description "Get geodetic stations located in an specific state in Brazil" --uri "https://servicodados.ibge.gov.br/api/v1/bdg/estado/{parameter.value('stateCode')}/estacoes" --type http --property "stateCode:string,The 2-letter brazilian state code (i.e., SC for Santa Catarina, SP for São Paulo, etc)" --required stateCode
wanaku toolset add toolsets/brazil.json -n "state-districts" --description "Get a list of all districts, their IDs and details from an specific state in Brazil" --uri "https://servicodados.ibge.gov.br/api/v1/localidades/estados/{parameter.value('stateCode')}/distritos" --type http --property "stateCode:string,The 2-letter brazilian state code (i.e., SC for Santa Catarina, SP for São Paulo, etc)" --required stateCode
wanaku toolset add toolsets/brazil.json -n "state-cities" --description "Get a list of all cities, their IDs and details from an specific state in Brazil" --uri "https://servicodados.ibge.gov.br/api/v1/localidades/estados/{parameter.value('stateCode')}/municipios" --type http --property "stateCode:string,The 2-letter brazilian state code (i.e., SC for Santa Catarina, SP for São Paulo, etc)" --required stateCode
wanaku toolset add toolsets/brazil.json -n "state-microregions" --description "Get a list of all micro-regions, their IDs and details from an specific state in Brazil" --uri "https://servicodados.ibge.gov.br/api/v1/localidades/estados/{parameter.value('stateCode')}/microrregioes" --type http --property "stateCode:string,The 2-letter brazilian state code (i.e., SC for Santa Catarina, SP for São Paulo, etc)" --required stateCode
wanaku toolset add toolsets/brazil.json -n "state-metropolitan-regions" --description "Get a list of all metropolitan regions, their IDs and details from an specific state in Brazil" --uri "https://servicodados.ibge.gov.br/api/v1/localidades/estados/{parameter.value('stateCode')}/regioes-metropolitanas" --type http --property "stateCode:string,The 2-letter brazilian state code (i.e., SC for Santa Catarina, SP for São Paulo, etc)" --required stateCode
wanaku toolset add toolsets/brazil.json -n "countries-geo" --description "Get a list of geographical country information" --uri "https://servicodados.ibge.gov.br/api/v1/localidades/paises" --type http
wanaku toolset add toolsets/brazil.json -n "states-geo" --description "Get a list of geographical state information" --uri "https://servicodados.ibge.gov.br/api/v1/localidades/estados" --type http
wanaku toolset add toolsets/brazil.json -n "countries-socio" --description "Get socio-economical details for a country" --uri "https://servicodados.ibge.gov.br/api/v1/paises/{parameter.value('country')}" --type http --property "country:string,The 2-letter country code (i.e, BR for Brazil, US for United States, CZ for Czech Republic, etc)" --required country
wanaku toolset add toolsets/brazil.json -n "ibge-news" --description "News published by the Brazilian Institute of Geography (IBGE)" --uri "http://servicodados.ibge.gov.br/api/v3/noticias/" --type http
wanaku toolset add toolsets/brazil.json -n "ibge-pesquisas" --description "Research published by the Brazilian Institute of Geography (IBGE)" --uri "https://servicodados.ibge.gov.br/api/v1/pesquisas" --type http
wanaku toolset add toolsets/brazil.json -n "ibge-pesquisas-specific" --description "Get details from an specific research published by the Brazilian Institute of Geography (IBGE)" --uri "https://servicodados.ibge.gov.br/api/v1/pesquisas/{parameter.value('researchId')}" --type http --property "researchId:int,The id of the research" --required researchId
wanaku toolset add toolsets/brazil.json -n "ibge-pesquisas-results" --description "Get results from an specific research published by the Brazilian Institute of Geography (IBGE)" --uri "https://servicodados.ibge.gov.br/api/v1/pesquisas/{parameter.value('researchId')}/resultados/{parameter.value('locationId')}" --type http --property "researchId:string,The id of the research" --required researchId --property "locationId:string,The id of the location (i.e., the ID of the city, state or micro-region)" --required locationId
wanaku toolset add toolsets/brazil.json -n "ibge-grid-state" --description "Get the geographical grid published by the Brazilian Institute of Geography (IBGE) for an specific state" --uri "https://servicodados.ibge.gov.br/api/v4/malhas/estados/{parameter.value('stateCode')}" --type http --property "stateCode:string,The 2-letter brazilian state code (i.e., SC for Santa Catarina, SP for São Paulo, etc)" --required stateCode
wanaku toolset add toolsets/brazil.json -n "ibge-grid-city" --description "Get the geographical grid published by the Brazilian Institute of Geography (IBGE) for an specific state" --uri "https://servicodados.ibge.gov.br/api/v4/malhas/municipios/{parameter.value('locationId')}" --type http --property "locationId:string,The city id of the location (i.e., the ID of the city)" --required locationId
wanaku toolset add toolsets/brazil.json -n "zip-code-cep" --description "Zipcode (CEP) to city lookup" --uri "https://brasilapi.com.br/api/cep/v2/{parameter.value('zipCode')}" --type http --property "zipCode:int,The zip code (also known as CEP) to lookup" --required zipCode
wanaku toolset add toolsets/brazil.json -n "cnpj-lookup" --description "Lookup company details from its fiscal identification (CNPJ)" --uri "https://brasilapi.com.br/api/cnpj/v1/{parameter.value('cnpj')}" --type http --property "cnpj:int,The company identification (also known as CNPJ) to lookup" --required cnpj
wanaku toolset add toolsets/brazil.json -n "brazilian-banks" --description "Get bank information, such as IDs, codes and full name" --uri "https://brasilapi.com.br/api/banks/v1" --type http
wanaku toolset add toolsets/brazil.json -n "brazilian-bank-info" --description "Get bank information, such as IDs, codes and full name from its code" --uri "https://brasilapi.com.br/api/banks/v1/{parameter.value('code')}" --type http --property "code:int,The bank code" --required cod
wanaku toolset add toolsets/brazil.json -n "brazilian-holidays" --description "Get Brazilian national holidays" --uri "https://brasilapi.com.br/api/feriados/v1/{parameter.value('year')}" --type http --property "year:int,The year to look for holidays" --required year
wanaku toolset add toolsets/brazil.json -n "interest-rates" --description "Get interest rate indicators" --uri "https://brasilapi.com.br/api/taxas/v1" --type http
wanaku toolset add toolsets/search.json -n "duckduckgo-search" --description "Search on the Internet using using DuckDuckGo" --uri "https://api.duckduckgo.com/?q={parameter.value('searchTerm')}&format=json&pretty=1" --type http  --property "searchTerm:string,The term or subject to search on the web" --required searchTerm
wanaku toolset add toolsets/fun.json -n "dog-facts" --description "Retrieve random facts about dogs" --uri "https://dogapi.dog/api/v2/facts?limit={parameter.value('limit')}" --type http  --property "limit:int,The count of facts to retrieve" --required limit
wanaku toolset add toolsets/fun.json -n "meow-facts" --description "Retrieve random facts about cats" --uri "https://meowfacts.herokuapp.com?count={parameter.value('count')}" --type http --property "count:int,The count of facts to retrieve" --required count